name: CI

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

concurrency:
    group: ci-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    # ! uncomment when finished setting up
    # check-workflow-files:
    #   runs-on: ubuntu-latest
    #   steps:
    #   # See: https://github.com/dorny/paths-filter
    #   #  quite useful, can be used to trigger certain tests
    #   #  only when certain files change.
    #     - uses: actions/checkout@v4
    #     - uses: dorny/paths-filter@v3
    #       id: changes
    #       with:
    #         filters: |
    #           workflow:
    #             - '.github/workflows/**'
    #     - name: Fail if workflow files are changed
    #       run: exit 1
    #       if: steps.changes.outputs.workflow == 'true'

    sveltecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "npm"

            - name: Install
              run: npm ci

            - name: Check
              run: npm run check

    test:
        timeout-minutes: 60
        runs-on: ${{ matrix.os }}
        
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest, windows-2019]
            fail-fast: false  # Continue running other OS tests even if one fails
            
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Install Playwright
              run: npm install playwright

            # - name: Install Playwright Browsers
            #   run: npx playwright install chromium

            # Use xvfb-run only on Ubuntu
            - name: Playwright tests
              if: matrix.os == 'ubuntu-latest'
              run: xvfb-run npm test

            # Regular run for other OS
            - name: Playwright tests
              if: matrix.os != 'ubuntu-latest'
              run: npm test
              
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report-${{ matrix.os }}
                  path: playwright-report/
                  retention-days: 30
                  
#   test:
#     runs-on: ${{ matrix.os }}

#     timeout-minutes: 30

#     strategy:
#       matrix:
#         os:
#           - ubuntu-latest
#           - macos-latest
#           - windows-latest
#           - windows-2019
#       fail-fast: false

#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 22
#           cache: 'npm'

#       - name: Install
#         run: npm ci

#       - name: Playwright Install
#         run: npx playwright install --with-deps

#       - name: Browser Tests
#         run: npm run test

