name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:

  # ! uncomment when finished setting up
  # check-workflow-files:
  #   runs-on: ubuntu-latest
  #   steps:
  #   # See: https://github.com/dorny/paths-filter
  #   #  quite useful, can be used to trigger certain tests 
  #   #  only when certain files change.
  #     - uses: actions/checkout@v4
  #     - uses: dorny/paths-filter@v3
  #       id: changes
  #       with:
  #         filters: |
  #           workflow:
  #             - '.github/workflows/**'
  #     - name: Fail if workflow files are changed
  #       run: exit 1
  #       if: steps.changes.outputs.workflow == 'true'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install
        run: npm ci

      # - name: Lint 
      #   run: npm run lint


  test:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - windows-2019
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install
        run: npm ci
        
      - name: Browser Tests
        run: npm run test

