name: Publish Package

on:
  push:
    tags:
      - 'v*'



jobs:
  publish:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: Release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node version to 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build:clean

      - name: Test All
        run: npm run test:all

      - name: Publish to npm
        run: npm run publish-ci ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Generate Changelog
      #   run: npx changelogithub
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}